insert into Addresses (address_id, city, number_street, number_building, post_index) values (1, 'Álimos', '448', 399, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (2, 'Duas Igrejas', '177', 257, '4580-373');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (3, 'Sritanjung', '8065', 54, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (4, 'Ngama', '157', 310, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (5, 'Zhucun', '079', 247, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (6, 'Huanan', '16108', 240, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (7, 'Bengras', '0', 382, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (8, 'Bangelan', '7067', 101, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (9, 'Kuala Lumpur', '6110', 139, '50913');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (10, 'Sukamulya', '7707', 235, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (11, 'Kiamba', '476', 368, '9514');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (12, 'Monguno', '362', 12, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (13, 'Su-dong', '02', 35, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (14, 'Ostrogozhsk', '7493', 168, '397855');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (15, 'Haparanda', '5405', 141, '953 34');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (16, 'Santa Cruz de la Sierra', '090', 195, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (17, 'Chenchang', '9', 390, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (18, 'Tomelilla', '910', 183, '273 35');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (19, 'La Habana Vieja', '897', 47, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (20, 'Linda Vista', '2', 178, '94475');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (21, 'Pinsk', '6', 394, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (22, 'Calinaoan Malasin', '659', 360, '3700');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (23, 'San Miguel', '5', 7, '39230');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (24, 'Hakodate', '016', 113, '704-8124');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (25, 'Afántou', '7', 174, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (26, 'Kandava', '3', 171, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (27, 'Zamarski', '03411', 226, '43-419');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (28, 'Manhiça', '10', 236, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (29, 'Kerek', '7', 365, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (30, 'Kapunduk', '33255', 342, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (31, 'Qiongshan', '1208', 167, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (32, 'High Prairie', '5', 278, 'L8N');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (33, 'Cahuacho', '61', 278, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (34, 'Meijiahe', '90', 221, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (35, 'Qingxi', '6290', 24, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (36, 'Huixing', '50', 19, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (37, 'Tyrnyauz', '07837', 225, '361624');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (38, 'Zhongxin', '3', 80, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (39, 'Los Angeles', '143', 390, '90035');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (40, 'Kebonkai', '751', 395, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (41, 'Caluire-et-Cuire', '79611', 341, '69649 CEDEX');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (42, 'Springbok', '241', 341, '8893');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (43, 'Dangbigih', '11', 363, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (44, 'Heishui', '088', 74, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (45, 'Valence', '919', 2, '26003 CEDEX');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (46, 'Caen', '91', 358, '14922 CEDEX 9');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (47, 'Barvinkove', '4202', 399, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (48, 'Berkovitsa', '427', 355, '3500');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (49, 'Leganes', '3115', 235, '28914');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (50, 'Byahoml’', '11', 111, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (51, 'Albertville', '153', 164, '73209 CEDEX');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (52, 'Shangyang', '67', 147, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (53, 'Tirah', '387', 220, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (54, 'Talok', '8291', 102, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (55, 'Jindong', '42165', 206, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (56, 'Lutou', '18', 122, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (57, 'Kostino', '9496', 73, '613060');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (58, 'Balayong', '3665', 367, '7213');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (59, 'Ponce', '493', 266, '00731');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (60, 'Hitachi', '83', 274, '319-1417');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (61, 'Vladikavkaz', '694', 120, '362049');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (62, 'Recarei', '57', 117, '4585-586');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (63, 'Novhorod-Sivers’kyy', '687', 294, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (64, 'Ovsyanka', '05342', 49, '216282');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (65, 'Kurnāz', '37770', 194, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (66, 'Rybnaya Sloboda', '996', 161, '422650');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (67, 'Yengimahalla', '969', 327, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (68, 'Tlogocilik', '3', 269, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (69, 'Pātan', '643', 85, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (70, 'Oinoússes', '825', 141, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (71, 'Kajiki', '50', 366, '899-5241');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (72, 'Nedakonice', '86', 245, '687 38');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (73, 'Basseterre', '542', 141, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (74, 'Pristina', '338', 59, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (75, 'Cigembor', '05', 163, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (76, 'Hezhang', '6419', 159, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (77, 'Bohus', '061', 320, '445 33');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (78, 'Shilong', '8', 271, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (79, 'Malian', '6838', 318, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (80, 'Kasoa', '948', 321, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (81, 'Round Rock', '01', 361, '78682');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (82, 'Lyon', '41992', 17, '69339 CEDEX 02');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (83, 'Yeysk', '506', 144, '404172');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (84, 'Kim Sơn', '0', 128, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (85, 'Soraya', '81', 287, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (86, 'Galatás', '2', 61, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (87, 'Richmond', '110', 382, '23272');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (88, 'Żurowa', '0', 369, '38-323');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (89, 'Pueblo Nuevo', '823', 344, '52332');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (90, 'Laiyang', '29628', 125, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (91, 'Chimbas', '4741', 79, '5413');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (92, 'Ploso', '54', 86, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (93, 'Bartolomé Masó', '82', 28, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (94, 'Piaocao', '8846', 26, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (95, 'Kandana', '64', 386, '11320');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (96, 'Kyzylorda', '41950', 55, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (97, 'Palatine', '91', 97, '60078');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (98, 'Tauranga', '22404', 371, '3144');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (99, 'Kozje', '735', 313, '3260');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (100, '''s-Hertogenbosch', '24345', 219, '5214');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (101, 'Armação', '42', 171, '59990-000');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (102, 'Genang', '45', 393, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (103, 'Södertälje', '4808', 395, '151 44');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (104, 'Sugito', '7499', 145, '345-0036');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (105, 'Pensacola', '4', 19, '32595');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (106, 'Gandara', '9', 338, '6706');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (107, 'Hitachi-Naka', '8', 227, '312-0063');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (108, 'Jinji', '632', 9, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (109, 'Lagodekhi', '60', 328, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (110, 'Rauma', '4526', 5, '26820');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (111, 'Tambo', '8', 252, '1701');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (112, 'Hegarmulya', '4284', 349, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (113, 'Torino', '81', 292, '10141');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (114, 'Santa Cruz do Bispo', '29501', 129, '4455-794');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (115, 'Kamiichi', '4', 4, '872-0511');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (116, 'Yongfu', '0', 16, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (117, 'La Condamine', '38204', 39, '98000');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (118, 'Liubo', '618', 212, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (119, 'Arras', '38261', 175, '62025 CEDEX');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (120, 'Bualan', '89307', 46, '9706');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (121, 'Barra de São Francisco', '0', 247, '29800-000');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (122, 'Zhovkva', '9', 363, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (123, 'Grojec', '89', 394, '32-615');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (124, 'Duas Igrejas', '1815', 130, '5210-046');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (125, 'Sidonganti', '297', 360, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (126, 'Jawornik Polski', '925', 210, '37-232');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (127, 'Nahrīn', '2374', 196, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (128, 'Nusajaya', '012', 80, '79632');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (129, 'Beberibe', '2612', 201, '62840-000');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (130, 'Ninghai', '9', 4, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (131, 'Jedlnia-Letnisko', '1769', 331, '26-630');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (132, 'Shouchun', '092', 96, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (133, 'Lyubech', '49507', 247, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (134, 'Estância Velha', '1', 342, '93600-000');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (135, 'Portel', '9625', 366, '68480-000');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (136, 'Lubenec', '96', 310, '439 83');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (137, 'Pandasan', '80', 1, '3714');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (138, 'Liulin', '03', 106, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (139, 'Kärdla', '2', 129, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (140, 'Bojongsari', '73', 110, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (141, 'Warugunung', '90017', 220, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (142, 'Curanilahue', '48518', 171, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (143, 'Krajan Selatan', '28304', 84, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (144, 'Shah Alam', '7189', 349, '40990');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (145, 'Horad Smalyavichy', '846', 172, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (146, 'Biankouma', '4', 7, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (147, 'Donskoy', '77', 98, '301767');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (148, 'Nanshao', '4', 142, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (149, 'Staroderevyankovskaya', '119', 48, '353721');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (150, 'Ylämaa', '4603', 181, '54410');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (151, 'Göteborg', '591', 322, '400 70');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (152, 'Gandong', '045', 122, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (153, 'Stochov', '85', 99, '273 03');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (154, 'El Paso', '3690', 297, '88553');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (155, 'Tournai', '8972', 314, '7536');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (156, 'Ratoath', '34276', 56, 'A85');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (157, 'Sidowayah Lor', '323', 74, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (158, 'Kutapanjang', '915', 389, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (159, 'Pag-asa', '79', 21, '8113');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (160, 'Windsor', '2', 311, 'J1S');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (161, 'Tanlad', '154', 184, '8010');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (162, 'Chortkiv', '1029', 235, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (163, 'Ragana', '74075', 339, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (164, 'Chisec', '6208', 373, '18006');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (165, 'Miramar', '03309', 186, '5143');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (166, 'Altavista', '0', 28, '32127');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (167, 'Agualva', '3812', 86, '9760-016');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (168, 'Huwan', '8', 283, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (169, 'Ocuviri', '97985', 87, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (170, 'Kobyzhcha', '1', 337, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (171, 'Iwase', '8864', 68, '948-0212');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (172, 'Igbo Ora', '6', 142, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (173, 'Kotlas', '9', 119, '443543');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (174, 'Novorossiysk', '5', 146, '353993');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (175, 'Paraiso', '08335', 73, '1104');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (176, 'Pinaring', '5', 272, '1110');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (177, 'Chipata', '3453', 59, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (178, 'Kurchatov', '53', 74, '307251');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (179, 'Oslo', '23', 192, '0323');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (180, 'Helsingborg', '170', 354, '256 62');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (181, 'Mikulintsy', '60587', 150, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (182, 'Sano', '0062', 232, '987-2363');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (183, 'Akora', '827', 376, '24131');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (184, 'Fristad', '2142', 301, '513 91');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (185, 'Boca Chica', '6', 258, '11102');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (186, 'Vasyshcheve', '35564', 301, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (187, 'Paris 02', '51', 289, '75075 CEDEX 02');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (188, 'Abade de Neiva', '8311', 82, '4750-005');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (189, 'Xuebu', '64797', 90, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (190, 'Turija', '82', 20, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (191, 'Chunhu', '17914', 54, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (192, 'Paoay', '4', 303, '2902');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (193, 'Lidong', '9', 270, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (194, 'Iecava', '67045', 17, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (195, 'Ayorou', '3', 110, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (196, 'Nine', '6', 292, '4775-446');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (197, 'Krasnokamsk', '17', 164, '397325');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (198, 'Lijiang', '341', 376, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (199, 'Balta', '43425', 281, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (200, 'Tabou', '1372', 237, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (201, 'Santa Rosa', '649', 334, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (202, 'Kimhae', '8', 147, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (203, 'Krotoszyn', '888', 222, '63-702');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (204, 'Dorp Tera Kora', '137', 135, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (205, 'Mahīn', '541', 288, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (206, 'Moog', '1024', 85, '9019');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (207, 'Lins', '407', 357, '16400-000');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (208, 'Tripoli', '12045', 325, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (209, 'Gujō', '276', 291, '501-4455');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (210, 'Al Majāridah', '900', 182, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (211, 'Talca', '27', 387, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (212, 'Sirnasari', '95205', 39, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (213, 'Bāft', '66328', 205, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (214, 'Páchni', '17558', 126, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (215, 'København', '81', 5, '1656');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (216, 'Mamfe', '65', 189, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (217, 'Macieira de Rates', '929', 146, '4755-264');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (218, 'Tagbilaran City', '9', 363, '6300');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (219, 'Xipu', '7053', 273, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (220, 'Taoxi', '12', 67, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (221, 'Leeds', '511', 304, 'LS6');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (222, 'Arras', '7', 355, '62010 CEDEX');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (223, 'São Miguel da Carreira', '16', 207, '4775-055');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (224, 'Lianpeng', '924', 125, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (225, 'Salem', '1700', 109, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (226, 'Ambalavao', '1299', 135, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (227, 'Hengxizhen', '367', 256, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (228, 'Bomomani', '08', 369, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (229, 'Mekarsari', '6577', 113, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (230, 'Ŭiju', '81', 353, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (231, 'Tashtagol', '2670', 169, '652993');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (232, 'Yabuli', '96', 48, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (233, 'Kuala Lumpur', '864', 82, '55908');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (234, 'Düsseldorf', '4', 186, '40225');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (235, 'Kakamega', '7', 13, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (236, 'Ambon', '03885', 388, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (237, 'Valladolid', '2402', 374, '47010');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (238, 'Altenberg bei Linz', '843', 270, '4210');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (239, 'Hronov', '1779', 50, '549 31');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (240, 'Laoqiao', '2593', 172, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (241, 'Shangpai', '2682', 370, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (242, 'Várzea da Serra', '7177', 97, '3610-193');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (243, 'São Miguel da Carreira', '19', 379, '4775-055');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (244, 'Sendung', '0', 55, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (245, 'Świdnica', '98262', 126, '66-008');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (246, 'Changchun', '613', 16, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (247, 'Brandfort', '0', 85, '9400');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (248, 'Vyshneve', '706', 200, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (249, 'Rumoi', '98475', 240, '518-0875');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (250, 'São Roque', '59', 135, '18130-000');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (251, 'Ansongo', '51', 247, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (252, 'Yagoua', '41', 226, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (253, 'Tairua', '44', 164, '3544');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (254, 'Nong Yasai', '1', 305, '72240');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (255, 'Blangpulo', '37', 242, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (256, 'Yunfu', '4', 11, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (257, 'Changning', '690', 195, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (258, 'Dolavón', '60', 151, '5531');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (259, 'Gafargaon', '9', 99, '2234');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (260, 'Eisen', '704', 340, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (261, 'Toki', '384', 176, '509-6251');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (262, 'Nantes', '627', 163, '44101 CEDEX 4');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (263, 'Kiev', '6496', 221, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (264, 'Gandajika', '0896', 36, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (265, 'Kimhae', '41120', 332, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (266, 'Maria', '795', 21, '6229');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (267, 'Murmansk', '46229', 267, '183985');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (268, 'Ilihan', '704', 271, '1745');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (269, 'Kuantan', '3', 176, '26040');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (270, 'Semang', '7', 315, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (271, 'Pampa del Infierno', '4', 389, '3708');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (272, 'Klembivka', '87', 371, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (273, 'Cambita Garabitos', '5750', 207, '11204');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (274, 'Yong’an', '68818', 251, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (275, 'Kachkanar', '447', 221, '624357');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (276, 'Conchucos', '1310', 196, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (277, 'Tanguiéta', '58', 200, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (278, 'Cigeulis', '4', 349, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (279, 'Bastan', '6449', 283, '658972');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (280, 'Petrikov', '606', 41, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (281, 'Micheng', '774', 159, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (282, 'Sinanju', '4458', 238, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (283, 'Jocotán', '66353', 326, '20005');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (284, 'Bucaramanga', '44', 12, '680011');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (285, 'Etinan', '544', 354, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (286, 'Acajutla', '2127', 309, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (287, 'Patrocínio', '4514', 42, '38740-000');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (288, 'Vila Velha de Ródão', '8281', 214, '6030-006');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (289, 'Pont Cassé', '763', 169, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (290, 'Yamazakichō-nakabirose', '72392', 2, '671-2536');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (291, 'Bader', '8', 104, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (292, 'Shitouhe', '31', 248, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (293, 'Wschowa', '78', 377, '67-400');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (294, 'Butajīra', '9', 258, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (295, 'Novocherkassk', '0', 315, '346408');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (296, 'Pāvilosta', '08294', 12, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (297, 'Sexiong', '0995', 8, null);
insert into Addresses (address_id, city, number_street, number_building, post_index) values (298, 'Sävedalen', '59', 383, '433 68');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (299, 'Vila Nova de Santo André', '707', 366, '7500-130');
insert into Addresses (address_id, city, number_street, number_building, post_index) values (300, 'Mora', '5', 49, '792 34');
